services:
  teateroen-server:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: teateroen-server
    userns_mode: "host"
    dns:
      - 100.100.100.100
      - 1.1.1.1
    dns_search:
      - tail84ebbf.ts.net
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_AUTH_ONCE: "true"
      TS_HOSTNAME: teateroen-server
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_SERVE_CONFIG: /config/generated/control-app-funnel.json
      TS_SERVE_TEMPLATE: /config/control-app-funnel.template.json
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"
      TS_ENABLE_HEALTH_CHECK: "true"
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME:-admin}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:-}
    volumes:
      - ./tailscale/config:/config
      - ./tailscale/state:/var/lib/tailscale
      - /dev:/host-dev
    devices:
      - /dev/net/tun:/dev/net/tun
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 116:* rmw"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
