srt:
  video_src: "srt://0.0.0.0:7701?mode=listener&latency=100&rcvbuf=67108864&fc=102400&tsbpdDelay=1000"
  video_sink: "srt://0.0.0.0:7702?mode=listener&latency=100&rcvbuf=67108864&fc=102400&tsbpdDelay=1000"
  audio_src: "srt://0.0.0.0:8801?mode=listener&latency=100&rcvbuf=67108864&fc=102400&tsbpdDelay=1000"
  audio_sink: "srt://0.0.0.0:8802?mode=listener&latency=100&rcvbuf=67108864&fc=102400&tsbpdDelay=1000"

fallback:
  video_A: "snow"
  audio_A: "sine"
  video_C: "ball"
  audio_C: "square"

encoding:
  video:
    bitrate: 1500
    key_int_max: 30
  audio:
    format: "opus"
