srt:
  input:
    node_A:
      uri: "srt://0.0.0.0:7001?mode=listener&latency=5000&rbuf=32768&wbuf=32768&tsbpdDelay=2000"
    node_C:
      uri: "srt://0.0.0.0:7002?mode=listener&latency=5000&rbuf=32768&wbuf=32768&tsbpdDelay=2000"
  output:
    node_B:
      uri: "srt://0.0.0.0:8001?mode=listener"
    node_D:
      uri: "srt://0.0.0.0:8002?mode=listener"

fallback:
  video_A: "snow"
  audio_A: "sine"
  video_C: "ball"
  audio_C: "square"

encoding:
  video:
    bitrate: 1500
    key_int_max: 30
  audio:
    format: "opus"
