server_ip: 178.249.52.14
streaming_settings_audio: "latency=100&rcvbuf=67108864&fc=102400&tsbpdDelay=1000"
streaming_settings_video: "latency=500&rbuf=327680&wbuf=327680&tsbpdDelay=2000"

ports:
  audio_send_tn: 8805
  audio_send_dk: 8806
  audio_receive_dk: 8807
  audio_receive_tn: 8808
  video_send_tn: 7701
  video_send_dk: 7702
  video_receive_dk: 7703
  video_receive_tn: 7704


audio:
  source: "alsasrc"
  format: "S16BE"
  rate: 32000
  channels: 2
  encoding_name: "L16"

video:
  source: "v4l2src device=/dev/video0"
  encoder: "x264enc"
  tune: "zerolatency"
  bitrate: 3000
  key_int_max: 15
  bframes: 0
  aud: true
  byte_stream: true
  option_str: ""
  config_interval: 1
  alignment: 7


